---
title: "Quantifying diversity in dinucleotide content across Eukaryotic kingdoms"
author: "Mark Ziemann & Nisha Paudel"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    fig_width: 5
    fig_height: 5
theme: cosmo
---


## Introduction

Here I will be calculating the Euclidean distance separating organisms of different


```{r,libs}

suppressPackageStartupMessages({
  library("vioplot")
  library("beeswarm")
  library("kableExtra")
  library("seqinr")
  library("gplots")
})

```

Load data.

```{r,load}

dat <- read.csv("new_all.csv")
head(dat)

```

Separate into groups.

 [1] "Mammals"       "Birds"         "Reptiles"      "Amphibians"   
 [5] "Fishes"        "Plants"        "Chlorophyta"   "Invertebrates"
 [9] "Fungi"         "Protozoa"   

```{r,sep_data}

unique(dat$class)

mammals <- subset(dat,class=="Mammals")
fishes <- subset(dat,class=="Fishes")
birds <- subset(dat,class=="Birds")
fungi <- subset(dat,class=="Fungi")
plants <- subset(dat,class=="Plants")
protozoa <- subset(dat,class=="Protozoa")
reptiles <- subset(dat,class=="Reptiles")
chlorophyta <- subset(dat,class=="Chlorophyta")
amphibians <- subset(dat,class=="Amphibians")
invertebrates <- subset(dat,class=="Invertebrates")

l <- list("mammals"=mammals, "fishes"=fishes, "birds"=birds, "fungi"=fungi,
  "plants"=plants, "protozoa"=protozoa, "reptiles"=reptiles, 
  "chlorophyta"=chlorophyta, "amphibians"=amphibians, "invertebrates"=invertebrates)

```

Now to examine the diversity with mean Eucledian distance.

```{r,dist1}

res <- lapply(l,function(df) {
  df$class <- NULL
  dfa <- aggregate(. ~ name, df, mean)
  rownames(dfa) <- dfa$name
  dfa$name <- NULL
  as.vector(dist(dfa))
})

message("mean")
lapply(res,mean)

message("median")
lapply(res,median)

res2 <- res[order(unlist(lapply(res,median)))]

par(mar=c(5,7,3,1))
vioplot(res2,horizontal=TRUE,las=1,main="distribution of Euclidean distance") ; grid()
barplot(unlist(lapply(res2,mean)),horiz=TRUE,las=1,main="mean Euclidean distance") ; grid()
barplot(unlist(lapply(res2,mean)),horiz=TRUE,las=1,main="median Euclidean distance") ; grid()

```

## Heatmaps

```{r,heatmaps}

chlorophyta$class = NULL
rownames(chlorophyta) <- chlorophyta$name
chlorophyta$name = NULL
hm_chlorophyta <- heatmap.2(as.matrix(chlorophyta),trace="none",main="chlorophyta",
  scale="none",mar=c(12,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

protozoa$class = NULL
rownames(protozoa) <- protozoa$name
protozoa$name = NULL
hm_protozoa <- heatmap.2(as.matrix(protozoa),trace="none", main="protozoa",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

invertebrates$class = NULL
rownames(invertebrates) <- invertebrates$name
invertebrates$name = NULL
hm_invertebrates <- heatmap.2(as.matrix(invertebrates),trace="none", main="invertebrates",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

mammals$class = NULL
rownames(mammals) <- mammals$name
mammals$name = NULL
hm_mammals <- heatmap.2(as.matrix(mammals),trace="none",main="mammals",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

fishes$class = NULL
fishes <- aggregate(. ~ name, fishes, mean)
rownames(fishes) <- fishes$name
fishes$name = NULL
hm_fishes <- heatmap.2(as.matrix(fishes),trace="none",main="fishes",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

birds$class = NULL
rownames(birds) <- birds$name
birds$name = NULL
hm_birds <- heatmap.2(as.matrix(birds),trace="none",main="birds",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

fungi$class = NULL
rownames(fungi) <- fungi$name
fungi$name = NULL
hm_fungi <- heatmap.2(as.matrix(fungi),trace="none",main="fungi",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

plants$class = NULL
rownames(plants) <- plants$name
plants$name = NULL
hm_plants <- heatmap.2(as.matrix(plants),trace="none",main="plants",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

reptiles$class = NULL
rownames(reptiles) <- reptiles$name
reptiles$name = NULL
hm_reptiles <- heatmap.2(as.matrix(reptiles),trace="none",main="reptiles",
  scale="none",mar=c(3,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

amphibians$class = NULL
rownames(amphibians) <- amphibians$name
amphibians$name = NULL
hm_amphibians <- heatmap.2(as.matrix(amphibians),trace="none",main="amphibians",
  scale="none",mar=c(12,12),cexRow=0.8, dendrogram="row", Colv=FALSE)

```

## Session

Session info

```{r,session}

sessionInfo()

```
